export const course_en = {
  syllabus: {
    header: "Workshop Syllabus",
    chapters: [
      {
        title: "Welcome, Program Overview, Platform Tour, and FAQs",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Getting to Know the Course and Our Goals",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Navigating the Platform and Course Resources",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "How We’ll Learn Together",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Initial Questions & Answers",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Important Dates and What to Expect",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 30,
        free: false,
      },
      {
        title: "Purpose & Values + Growth Mindset",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Finding Your Purpose in Real Estate Investing",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Key Values for Real Estate Success",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Building a Resilient Investor Mindset",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Recognizing and Shifting Limiting Beliefs",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Tools to Stay Motivated and Focused",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 30,
        free: false,
      },
      {
        title: "Comprehensive Plan + Financial Roadmap + Accountability Buddy",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Mapping Out Your Big Picture Plan",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Building a Financial Plan for Success",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Why Having an Accountability Partner Matters",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Setting Clear Financial and Investment Goals",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Planning Exercises for Your Path Forward",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 60,
        free: false,
      },
      {
        title: "Choosing Your Strategy + Spotting Opportunities",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Exploring the Right Strategy for You",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Where to Find the Best Market Opportunities",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Weighing the Risks and Rewards of Each Approach",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Organizing Your Time and Resources",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Real-World Strategy Examples and Case Studies",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Building Your Team + Checking In on Progress",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Who You Need on Your Investment Team",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Finding Great Partners and Collaborators",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Tools to Keep Your Plan on Track",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Overcoming Roadblocks and Celebrating Wins",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Reviewing and Adjusting Your Strategy with the Team",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Buying Strategies: Flipping + Property Improvements",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Understanding the Flipping Market",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Choosing the Right Properties for Renovations",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Time & Budget Planning for Flipping Success",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Maximizing Profits in Renovations",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Lessons Learned from Real Flipping Projects",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Buying Strategies: Long-Term and Short-Term Rentals",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Rental Market Insights and Trends",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Picking Profitable Rental Properties",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Long-Term vs. Short-Term Rentals: Which is Right for You?",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Tips for Boosting Rental Income",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Real-World Examples from the Rental Market",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Generating Leads and Finding Deals",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Using Digital Marketing to Attract Leads",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "How to Prospect and Connect on Social Media",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Tools to Manage and Track Your Leads",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Networking and Partnerships to Grow Opportunities",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Measuring ROI on Lead Generation Efforts",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 180,
        free: false,
      },
      {
        title: "Mastering Negotiation",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Essential Negotiation Skills for Real Estate",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Tips for Getting the Best Price",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Handling Common Objections with Ease",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Practical Negotiation Exercises",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Success Stories and Real-World Examples",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Financing Options + Advanced Money Strategies",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Understanding Financing Options and How to Get Them",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Pros & Cons of Different Types of Financing",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Advanced Financing: Hard Money and Beyond",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Planning Payments and Amortization",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Success Stories: Financing Real Estate Investments",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "The Ultimate Checklist for Buying and Selling",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Creating a Personalized Buying Checklist",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Key Legal and Technical Steps in Purchasing",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Prepping for Sale to Maximize Value",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Getting Your Documents in Order",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Examples and Customizing Your Checklists",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Contracts + Finding Great Tenants",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Types of Contracts and Essential Clauses",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Key Legal Points in Rental Agreements",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Tips for Finding Reliable Tenants",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Financial Criteria for Tenant Evaluation",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Sample Contracts and How to Customize Them",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Fernando’s Guide to Renovations",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Planning and Designing Effective Renovations",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Choosing Materials and Managing Costs",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Time Management and Team Coordination",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Overseeing Work and Ensuring Quality",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Lessons Learned from Successful Renovation Projects",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Renovations + Home Staging for Maximum Impact",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "The Basics and Benefits of Home Staging",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Key Tools and Techniques for Effective Staging",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Furniture Selection and Eye-Catching Design",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Cost-Benefit Analysis on Staging",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Real-Life Success Stories in Home Staging",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Smart Tax Strategies",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Key Taxes for Real Estate Transactions",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Tax Planning Tips to Save Money",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Tax Essentials for Rental and Sales Income",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Deductions and Tax Benefits You Can Use",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Real-World Examples of Smart Tax Planning",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Becoming an Intermediary",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "The Role of an Intermediary in Real Estate",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Strategies for Finding and Working with Clients",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Closing Deals as an Intermediary",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Following Up and Keeping Clients Happy",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Case Studies on Successful Intermediation",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Wrapping Up and Looking Ahead",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Key Takeaways from the Course",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Reviewing Your Achievements and Next Goals",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Planning Your Next Steps in Real Estate",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Self-Assessment and Setting Future Goals",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Final Tips and Recommendations for Success",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
    ],
  },
};
