export const course_es = {
  syllabus: {
    header: "Programa del Taller",
    chapters: [
      {
        title:
          "Bienvenida, Descripción del Programa, Recorrido por la Plataforma y Preguntas Frecuentes",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Conociendo el Curso y Nuestros Objetivos",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Navegando por la Plataforma y Recursos del Curso",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Cómo Aprenderemos Juntos",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Preguntas y Respuestas Iniciales",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Fechas Importantes y Qué Esperar",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 30,
        free: false,
      },
      {
        title: "Propósito y Valores + Mentalidad de Crecimiento",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Encontrando Tu Propósito en la Inversión Inmobiliaria",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Valores Clave para el Éxito en Bienes Raíces",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Construyendo una Mentalidad Resiliente de Inversor",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Reconociendo y Cambiando Creencias Limitantes",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Herramientas para Mantenerse Motivado y Enfocado",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 30,
        free: false,
      },
      {
        title: "Estrategias de Inversión en Bienes Raíces",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Explorando la Estrategia Adecuada para Ti",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Dónde Encontrar las Mejores Oportunidades de Mercado",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Evaluando los Riesgos y Recompensas de Cada Enfoque",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Organizando Tu Tiempo y Recursos",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Ejemplos de Estrategias del Mundo Real y Estudios de Caso",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Construyendo Tu Equipo + Revisando el Progreso",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Quién Necesitas en Tu Equipo de Inversión",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Encontrando Grandes Socios y Colaboradores",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Herramientas para Mantener Tu Plan en Marcha",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Superando Obstáculos y Celebrando Éxitos",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Revisando y Ajustando Tu Estrategia con el Equipo",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Estrategias de Compra: Flipping + Mejoras de Propiedad",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Entendiendo el Mercado de Flipping",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Eligiendo las Propiedades Adecuadas para Renovaciones",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title:
              "Planificación de Tiempo y Presupuesto para el Éxito en Flipping",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Maximizando las Ganancias en Renovaciones",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Lecciones Aprendidas de Proyectos Reales de Flipping",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Estrategias de Compra: Alquileres a Largo y Corto Plazo",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Perspectivas y Tendencias del Mercado de Alquileres",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Eligiendo Propiedades de Alquiler Rentables",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title:
              "Alquileres a Largo Plazo vs. Corto Plazo: ¿Cuál es el Adecuado para Ti?",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Consejos para Aumentar los Ingresos por Alquiler",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Ejemplos del Mundo Real del Mercado de Alquileres",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Generación de Leads y Encontrar Ofertas",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Usando Marketing Digital para Atraer Leads",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Cómo Prospectar y Conectar en Redes Sociales",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Herramientas para Gestionar y Rastrear Tus Leads",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Networking y Asociaciones para Crear Oportunidades",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Midiendo el ROI en Esfuerzos de Generación de Leads",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 180,
        free: false,
      },
      {
        title: "Dominando la Negociación",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Habilidades Esenciales de Negociación para Bienes Raíces",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Consejos para Conseguir el Mejor Precio",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Manejando Objeciones Comunes con Facilidad",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Ejercicios Prácticos de Negociación",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Historias de Éxito y Ejemplos del Mundo Real",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Opciones de Financiamiento + Estrategias Avanzadas de Dinero",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title:
              "Entendiendo las Opciones de Financiamiento y Cómo Obtenerlas",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Pros y Contras de Diferentes Tipos de Financiamiento",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Financiamiento Avanzado: Dinero Duro y Más Allá",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Planificación de Pagos y Amortización",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title:
              "Historias de Éxito: Financiamiento de Inversiones Inmobiliarias",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "La Lista de Verificación Definitiva para Comprar y Vender",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title:
              "Creando una Lista de Verificación Personalizada para Comprar",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Pasos Legales y Técnicos Clave en la Compra",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Preparándose para la Venta para Maximizar el Valor",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Poniendo en Orden Tus Documentos",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Ejemplos y Personalización de Tus Listas de Verificación",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Contratos + Encontrar Grandes Inquilinos",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Tipos de Contratos y Cláusulas Esenciales",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Puntos Legales Clave en los Acuerdos de Alquiler",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Consejos para Encontrar Inquilinos Confiables",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Criterios Financieros para Evaluación de Inquilinos",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Contratos de Muestra y Cómo Personalizarlos",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Guía de Fernando para Renovaciones",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Planificación y Diseño de Renovaciones Efectivas",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Elección de Materiales y Gestión de Costos",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Gestión del Tiempo y Coordinación del Equipo",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Supervisión del Trabajo y Aseguramiento de la Calidad",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Lecciones Aprendidas de Proyectos de Renovación Exitosos",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Renovaciones + Home Staging para Máximo Impacto",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Los Fundamentos y Beneficios del Home Staging",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Herramientas y Técnicas Clave para un Staging Efectivo",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Selección de Muebles y Diseño Atractivo",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Análisis de Costos y Beneficios del Staging",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Historias de Éxito en Home Staging",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Estrategias Inteligentes de Impuestos",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Impuestos Clave para Transacciones Inmobiliarias",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Consejos de Planificación Fiscal para Ahorrar Dinero",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title:
              "Ejemplos del Mundo Real de Planificación Fiscal Inteligente",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Convirtiéndose en Intermediario",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "El Papel de un Intermediario en Bienes Raíces",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Estrategias para Encontrar y Trabajar con Clientes",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Cerrando Tratos como Intermediario",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Seguimiento y Manteniendo a los Clientes Felices",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Estudios de Caso sobre Intermediación Exitosa",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Concluyendo y Mirando Hacia Adelante",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Conclusiones Clave del Curso",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Revisando Tus Logros y Próximos Objetivos",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Planificando Tus Próximos Pasos en Bienes Raíces",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Autoevaluación y Establecimiento de Metas Futuras",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Consejos Finales y Recomendaciones para el Éxito",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title:
          "Plan Integral + Hoja de Ruta Financiera + Compañero de Responsabilidad",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Trazando Tu Plan General",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Construyendo un Plan Financiero para el Éxito",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Por Qué Tener un Compañero de Responsabilidad Importa",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Estableciendo Metas Financieras y de Inversión Claras",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Ejercicios de Planificación para Tu Camino a Seguir",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 60,
        free: false,
      },
      {
        title: "Eligiendo Tu Estrategia + Detectando Oportunidades",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Explorando la Estrategia Adecuada para Ti",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Dónde Encontrar las Mejores Oportunidades de Mercado",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Evaluando los Riesgos y Recompensas de Cada Enfoque",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Organizando Tu Tiempo y Recursos",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Ejemplos de Estrategias del Mundo Real y Estudios de Caso",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
    ],
  },
  testimonials: {
    list: [
      {
        avatar: "",
        name: "Luisma",
        role: "",
        quotelong:
          "En vertigo, sentío para mí ha sido bastante más que un curso. Empecé de una forma muy, muy potente y te planteas muchas cosas. A mí me recordó poco a la película de Karate Kid, cuando, cuando el chaval decía, a lo decir, al tercer apular será que tiene que ver esto con el Karate, pues en este curso, a mí me paso al principio un poco esto de que tiene que ver todo esto con las inversiones y realmente para mí ha sido increíble la forma tan potente en la que empieza haciendo un cambio de mentalidad para dar te cuenta de todo lo que puedes hacer como inversor y como te hacen cambiar la mentalidad para ser inversor. Lo más importante obviamente es que en que en que en que en te ayuda a ello, tanto a gel María como Guillermo son las personas que son son por su cercanía, por su humanidad, y porque te demuestran lo buena persona que son y no buena persona que puede ser siendo un inversor, el ser inversor no quiere decir, no quiere decir nada malo, no quiere decir que se es un trepa, que se es un tío agresivo, en absoluto, ellos te enseñan un poco a valorar todo lo bueno que se puede hacer también haciendo inversiones, eso es bueno para todos. Y bueno, a mi me ha llevado bastante el nivel de en realidad, que nos han enculcado, pero luego también hace el canía y sobre todo la humanidad, porque en este sector es algo que a lo mejor no está tan tan la flor de piel o tan bien explicado desde algunos sectores, no que puede ser, hasta puede estar mal visto, pero a mí la verdad es que me han encantado, me han cambiado totalmente la mentalidad de respeto las inversiones, respeto a tu espetal mismo, me he hecho cambiar muchas falsetas de mi vida en cuanto a profesional y a personal, para precisamente poder llevar a ser un buen inversor, así que no se me ocurre mucho más que deciros, porque lo mejor es y lo descubriendo y que os deje solprender también porque muchas cosas que la gente que empieza al curso no sabe lo que les espera y es mucho más que un curso de inversión, así que lo recomiendo.",
        quoteshort:
          "Este curso me cambió la mentalidad sobre las inversiones, transformándome en un mejor inversor tanto profesional como personalmente.",
      },
      {
        avatar: "",
        name: "Carlos Niearnau",
        role: "",
        quotelong:
          "Hola, hola a todos, espero que estés bien, mi nombre es Carlos Mirnau y no soy participante de la primera edición de DCS y os voy a explicar realmente mi experiencia para que tengáis una, no te viene a referencia, eh, un poco sobremina al final de la mis simplemente el sal de un desmobiliario y es quería comprar un, quiero comprar un piso para obtener una fonte ingresos adicional. Yo vi el, un acercuso a través del que bien, no conocía y hermoso, pero había un vídeo que había colado a él, me interesa en términos de YouTube, como su mente muchos de nosotros ahora estáis viendo, y nada al mente me gustaron mucho, me parecieron y hermoso en la gemalía de las personas estetinales que saben mucho el tema, y nada entonces me comentaron para contarme el curso Hacido en las experiencias estetinales de 3 meses, pero aún sí, y nada al final como no se se ha visto el plan y no así, pero cubre, digamos, las diferentes áreas que saber, pero bueno, al final comentaros que lo más importante no es la teoría, ya que la teoría la podéis encontrar en cualquier otro sitio, en internet, en libros y de manera gratuita, y un poco lo que os quería destacar y que es lo que más me ha gustado el curso, es el grupo que se quería, ya que al final considero poco creeré es una comunidad, la con descontarte con nosotros que somos ICS uno y en allo durante estos tres meses ya unas horas y hemos tenido un grupo de las ventias personas que hemos participado, pasamos oportunidades cada una, cada día noticias, entonces el cine estamos muy en contacto, incluso ahora estamos participando en la comprar en piso en Madrid. Entonces al final un poco yo lo que os vendría el curso es realmente esta experiencia de comunidad que es la que se crea y si es verdad que sobre todo para la gente Madrid es un poco más fuerte porque su la vez más gente ahí y al final en Madrid ya habréis que también ahí no más oportunidades pero está una cosita más. Pero en ese de Barcelona también no tiene unas cuentas este final tenemos un grupo aquí que también hemos hecho a una querada y esperamos seguir bien donos y al final es un poco lo más importante para mí esto. El grupo el grupo que hemos creado y nada que, al final, después de todo lo que se aprende las diferentes clases que tenéis que basabado o el día que digáis, al final si tenéis cualquier tipo de dudas, siempre tenéis a hacer María o a Guillermo, al final, son dos personas que hemos argumentado, sabe, en mucho, ya tienen más de más experiencia en el tema y que os van a ayudar mucho, sí, siempre es en el curso. Y nada, así para acabar ya, lo recomiendo, recomiendo que, que es la puntés ya que es una buena experiencia, que al final en los lados de tomar, no como un coste al mismo, sino como una impresión a futuro, bueno, muchas gracias y a ver si no es el más pante, no, la feo.",
        quoteshort:
          "Recomiendo el curso por la experiencia de comunidad que se crea y el apoyo constante de los instructores.",
      },
    ],
  },
};
