export const course_es = {
  syllabus: {
    header: "Programa del Taller",
    chapters: [
      {
        title: "Bienvenida, Descripción del Programa, Recorrido por la Plataforma y Preguntas Frecuentes",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Conociendo el Curso y Nuestros Objetivos",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Navegando por la Plataforma y Recursos del Curso",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Cómo Aprenderemos Juntos",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Preguntas y Respuestas Iniciales",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Fechas Importantes y Qué Esperar",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 30,
        free: false,
      },
      {
        title: "Propósito y Valores + Mentalidad de Crecimiento",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Encontrando Tu Propósito en la Inversión Inmobiliaria",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Valores Clave para el Éxito en Bienes Raíces",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Construyendo una Mentalidad Resiliente de Inversor",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Reconociendo y Cambiando Creencias Limitantes",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Herramientas para Mantenerse Motivado y Enfocado",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 30,
        free: false,
      },
      {
        title: "Estrategias de Inversión en Bienes Raíces",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Explorando la Estrategia Adecuada para Ti",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Dónde Encontrar las Mejores Oportunidades de Mercado",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Evaluando los Riesgos y Recompensas de Cada Enfoque",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Organizando Tu Tiempo y Recursos",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Ejemplos de Estrategias del Mundo Real y Estudios de Caso",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Construyendo Tu Equipo + Revisando el Progreso",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Quién Necesitas en Tu Equipo de Inversión",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Encontrando Grandes Socios y Colaboradores",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Herramientas para Mantener Tu Plan en Marcha",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Superando Obstáculos y Celebrando Éxitos",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Revisando y Ajustando Tu Estrategia con el Equipo",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Estrategias de Compra: Flipping + Mejoras de Propiedad",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Entendiendo el Mercado de Flipping",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Eligiendo las Propiedades Adecuadas para Renovaciones",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Planificación de Tiempo y Presupuesto para el Éxito en Flipping",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Maximizando las Ganancias en Renovaciones",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Lecciones Aprendidas de Proyectos Reales de Flipping",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Estrategias de Compra: Alquileres a Largo y Corto Plazo",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Perspectivas y Tendencias del Mercado de Alquileres",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Eligiendo Propiedades de Alquiler Rentables",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Alquileres a Largo Plazo vs. Corto Plazo: ¿Cuál es el Adecuado para Ti?",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Consejos para Aumentar los Ingresos por Alquiler",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Ejemplos del Mundo Real del Mercado de Alquileres",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Generación de Leads y Encontrar Ofertas",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Usando Marketing Digital para Atraer Leads",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Cómo Prospectar y Conectar en Redes Sociales",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Herramientas para Gestionar y Rastrear Tus Leads",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Networking y Asociaciones para Crear Oportunidades",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Midiendo el ROI en Esfuerzos de Generación de Leads",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 180,
        free: false,
      },
      {
        title: "Dominando la Negociación",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Habilidades Esenciales de Negociación para Bienes Raíces",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Consejos para Conseguir el Mejor Precio",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Manejando Objeciones Comunes con Facilidad",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Ejercicios Prácticos de Negociación",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Historias de Éxito y Ejemplos del Mundo Real",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Opciones de Financiamiento + Estrategias Avanzadas de Dinero",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Entendiendo las Opciones de Financiamiento y Cómo Obtenerlas",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Pros y Contras de Diferentes Tipos de Financiamiento",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Financiamiento Avanzado: Dinero Duro y Más Allá",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Planificación de Pagos y Amortización",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Historias de Éxito: Financiamiento de Inversiones Inmobiliarias",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "La Lista de Verificación Definitiva para Comprar y Vender",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Creando una Lista de Verificación Personalizada para Comprar",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Pasos Legales y Técnicos Clave en la Compra",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Preparándose para la Venta para Maximizar el Valor",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Poniendo en Orden Tus Documentos",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Ejemplos y Personalización de Tus Listas de Verificación",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Contratos + Encontrar Grandes Inquilinos",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Tipos de Contratos y Cláusulas Esenciales",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Puntos Legales Clave en los Acuerdos de Alquiler",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Consejos para Encontrar Inquilinos Confiables",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Criterios Financieros para Evaluación de Inquilinos",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Contratos de Muestra y Cómo Personalizarlos",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Guía de Fernando para Renovaciones",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Planificación y Diseño de Renovaciones Efectivas",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Elección de Materiales y Gestión de Costos",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Gestión del Tiempo y Coordinación del Equipo",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Supervisión del Trabajo y Aseguramiento de la Calidad",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Lecciones Aprendidas de Proyectos de Renovación Exitosos",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Renovaciones + Home Staging para Máximo Impacto",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Los Fundamentos y Beneficios del Home Staging",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Herramientas y Técnicas Clave para un Staging Efectivo",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Selección de Muebles y Diseño Atractivo",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Análisis de Costos y Beneficios del Staging",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Historias de Éxito en Home Staging",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Estrategias Inteligentes de Impuestos",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Impuestos Clave para Transacciones Inmobiliarias",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Consejos de Planificación Fiscal para Ahorrar Dinero",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Ejemplos del Mundo Real de Planificación Fiscal Inteligente",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Convirtiéndose en Intermediario",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "El Papel de un Intermediario en Bienes Raíces",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Estrategias para Encontrar y Trabajar con Clientes",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Cerrando Tratos como Intermediario",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Seguimiento y Manteniendo a los Clientes Felices",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Estudios de Caso sobre Intermediación Exitosa",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Concluyendo y Mirando Hacia Adelante",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Conclusiones Clave del Curso",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Revisando Tus Logros y Próximos Objetivos",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Planificando Tus Próximos Pasos en Bienes Raíces",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Autoevaluación y Establecimiento de Metas Futuras",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Consejos Finales y Recomendaciones para el Éxito",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
      {
        title: "Plan Integral + Hoja de Ruta Financiera + Compañero de Responsabilidad",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Trazando Tu Plan General",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Construyendo un Plan Financiero para el Éxito",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Por Qué Tener un Compañero de Responsabilidad Importa",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Estableciendo Metas Financieras y de Inversión Claras",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Ejercicios de Planificación para Tu Camino a Seguir",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 60,
        free: false,
      },
      {
        title: "Eligiendo Tu Estrategia + Detectando Oportunidades",
        description: "",
        sections: [
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Explorando la Estrategia Adecuada para Ti",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Dónde Encontrar las Mejores Oportunidades de Mercado",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Evaluando los Riesgos y Recompensas de Cada Enfoque",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Organizando Tu Tiempo y Recursos",
            duration: 0,
            watchlink: "",
          },
          {
            preview: false,
            previewlink: "",
            type: "lecture",
            title: "Ejemplos de Estrategias del Mundo Real y Estudios de Caso",
            duration: 0,
            watchlink: "",
          },
        ],
        totalduration: 220,
        free: false,
      },
    ],
  },
};
